version: "3.3"
services:
  node-0:
    build:
      context: .
      dockerfile: Dockerfile.Local
    ports:
      - "5000:80"
      - "5001:8080"
  node-1:
    build:
      context: .
      dockerfile: Dockerfile.Local
    ports:
      - "5010:80"
      - "5011:8080"
  node-2:
    build:
      context: .
      dockerfile: Dockerfile.Local
    ports:
      - "5020:80"
      - "5021:8080"