version: "3.3"
services:
  node-0:
    build:
      context: .
      dockerfile: samples/Nyris.Crdt.AspNetExample/Dockerfile
    environment:
      - NODE_NAME=node-0
    ports:
      - "5000:80"
      - "5001:8080"
  node-1:
    build:
      context: .
      dockerfile: samples/Nyris.Crdt.AspNetExample/Dockerfile
    environment:
      - NODE_NAME=node-1
    ports:
      - "5010:80"
      - "5011:8080"
  node-2:
    build:
      context: .
      dockerfile: samples/Nyris.Crdt.AspNetExample/Dockerfile
    environment:
      - NODE_NAME=node-2
    ports:
      - "5020:80"
      - "5021:8080"