global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
scrape_configs:
- job_name: CRDT_Metrics
  honor_timestamps: true
  scrape_interval: 5s  
  scrape_timeout: 1s  
  metrics_path: /metrics  
  scheme: http  
  static_configs:  
  - targets:  
    - host.docker.internal:5000
    - host.docker.internal:5010
    - host.docker.internal:5020