apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: distributed-prototype-test
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: sample-app
    version: {{ VERSION }}
    commit: {{ COMMIT }}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        version: {{ VERSION }}
        commit: {{ COMMIT }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
        prometheus.io/path: '/metrics'
    spec:
      serviceAccountName: sample-app
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sample-app
                topologyKey: kubernetes.io/hostname
      containers:
        - name: app
          image: {{ IMAGE }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              cpu: 500m
              memory: 3Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 600
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 2
          ports:
            - containerPort: 8080
              name: grpc
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ ASPNETCORE_ENVIRONMENT }}
            - name: OpenTelemetry__ServiceName
              value: distributed-prototype-test.sample-app
            - name: OpenTelemetry__Exporter
              value: jaeger
            - name: OpenTelemetry__Jaeger__Endpoint
              value: udp://jaeger-agent.istio-system.svc.cluster.local:6831
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          secret:
            secretName: distributed-prototype-test-sample-app-config-v0.1.0
