apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app
  namespace: distributed-prototype-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-app:pod-finder
  namespace: distributed-prototype-test
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-app:list-pods
  namespace: distributed-prototype-test
subjects:
  - kind: ServiceAccount
    name: sample-app
    namespace: distributed-prototype-test
roleRef:
  kind: ClusterRole
  name: sample-app:pod-finder
  apiGroup: rbac.authorization.k8s.io
