using System.ServiceModel;
using System.Threading.Tasks;
using Nyris.Crdt.Distributed.Model;

namespace Nyris.Crdt.Distributed
{
    [ServiceContract]
    public interface IProxy<TDto>
    {
        [OperationContract]
        // ReSharper disable once OperationContractWithoutServiceContract - service contract is generated by SourceGenerator
        Task<TDto> SendAsync(WithId<TDto> dto);
    }
}